server:
  port: 8090
#============== kafka ===================
kafka:
  consumer:
    zookeeper.connect: 119.45.206.237:2181
    servers: 119.45.206.237:9092
    enable.auto.commit: true
    session.timeout: 6000
    auto.commit.interval: 100
    auto.offset.reset: latest
    topic: test
    group.id: test
    concurrency: 2
  producer:
    servers: 119.45.206.237:9092
    retries: 0
    #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
    batch.size: 4096
    linger: 1
    buffer.memory: 40960
